namespace Some1.Play.Info
{
    public enum CharacterId : short
    {
        Player1,
        Player2,
        Player3,
        Player4,
        Player5,
        Player6,

        Mob1,
        Mob2,
        Mob3,
        Mob4,

        Chief1,
        Chief2,
        
        Boss1,
        Boss2,
        Boss3,
        Boss4,
        Boss5,
        Boss6,

        Plant1,
        Plant2,
        Plant3,
        Plant4,
        Plant5,
        Plant6,
        Plant7,
        Plant8,

        Animal1,
        Animal2,
        Animal3,
        Animal4,
        Animal5,

        Summon1,

        Box,

        Fence1,

        Landmark1,

        Barrier1,

        Water1,

        Missile1,
        Missile2,
        Missile3,
        Missile4,
        Missile5,
        Missile6,
        Missile7,
        Missile8,
        Missile9,
        Missile10,
        Missile11,
        Missile12,
        Missile13,
        Missile14,
        Missile15,
        Missile16,
        Missile17,
        Missile18,
        Missile19,
        Missile20,
        Missile21,
        Missile22,
        Missile23,
        Missile24,
        Missile25,
        Missile26,
        Missile27,
        Missile28,
        Missile29,
        Missile30,
        Missile31,
        Missile32,

        Explosion1,
        Explosion2,
        Explosion3,
        Explosion4,
        Explosion5,
        Explosion6,
        Explosion7,
        Explosion8,
        Explosion9,
        Explosion10,
        Explosion11,
        Explosion12,
        Explosion13,
        Explosion14,
        Explosion15,
        Explosion16,
        Explosion17,
        Explosion18,
        Explosion19,
        Explosion20,
        Explosion21,
        Explosion22,
        Explosion23,
        Explosion24,
        Explosion25,
        Explosion26,
        Explosion27,
        Explosion28,
        Explosion29,
        Explosion30,
        Explosion31,
        Explosion32,

        Magic1,
        Magic2,
        Magic3,
        Magic4,
        Magic5,
        Magic6,
        Magic7,

        Booster1,
        Booster2,

        Specialty1,
        Specialty2,
        Specialty3,
        Specialty4,
        Specialty5,
        Specialty6,
        Specialty7,
        Specialty8,
        Specialty9,
        Specialty10,
        Specialty11,
        Specialty12,
        Specialty13,
        Specialty14,
        Specialty15,
        Specialty16,
        Specialty17,
        Specialty18,
        Specialty19,
        Specialty20,
        Specialty21,
        Specialty22,
        Specialty23,
        Specialty24,
        Specialty25,
        Specialty26,
        Specialty27,
        Specialty28,
        Specialty29,
        Specialty30,

        WarpOut1,
        WarpOut2,
        WarpIn1,
        WarpIn2,

        Like0,
        Like1,
        Like2,
        Like3,
        Like4,
        Like5,
        Like6,
        Like7,
        Like8,

        Roadworks,
    }
}
