using System.Collections.Generic;

namespace Some1.Play.Info.Alpha
{
    public static class AlphaCharacterSkinInfosFactory
    {
        public static IEnumerable<CharacterSkinInfo> Create() => new CharacterSkinInfo[]
        {
            new(new(CharacterId.Player1, SkinId.Skin0)),
            new(new(CharacterId.Player1, SkinId.Skin1)),
            new(new(CharacterId.Player1, SkinId.Skin2)),
            new(new(CharacterId.Player1, SkinId.Skin3)),
            new(new(CharacterId.Player1, SkinId.Skin4)),
            new(new(CharacterId.Player1, SkinId.Skin5)),

            new(new(CharacterId.Player2, SkinId.Skin0)),
            new(new(CharacterId.Player2, SkinId.Skin1)),
            new(new(CharacterId.Player2, SkinId.Skin2)),
            new(new(CharacterId.Player2, SkinId.Skin3)),
            new(new(CharacterId.Player2, SkinId.Skin4)),
            new(new(CharacterId.Player2, SkinId.Skin5)),

            new(new(CharacterId.Player3, SkinId.Skin0)),
            new(new(CharacterId.Player3, SkinId.Skin1)),
            new(new(CharacterId.Player3, SkinId.Skin2)),
            new(new(CharacterId.Player3, SkinId.Skin3)),
            new(new(CharacterId.Player3, SkinId.Skin4)),
            new(new(CharacterId.Player3, SkinId.Skin5)),

            new(new(CharacterId.Player4, SkinId.Skin0)),
            new(new(CharacterId.Player4, SkinId.Skin1)),
            new(new(CharacterId.Player4, SkinId.Skin2)),
            new(new(CharacterId.Player4, SkinId.Skin3)),
            new(new(CharacterId.Player4, SkinId.Skin4)),
            new(new(CharacterId.Player4, SkinId.Skin5)),

            new(new(CharacterId.Player5, SkinId.Skin0)),
            new(new(CharacterId.Player5, SkinId.Skin1)),
            new(new(CharacterId.Player5, SkinId.Skin2)),
            new(new(CharacterId.Player5, SkinId.Skin3)),
            new(new(CharacterId.Player5, SkinId.Skin4)),
            new(new(CharacterId.Player5, SkinId.Skin5)),

            new(new(CharacterId.Player6, SkinId.Skin0)),
            new(new(CharacterId.Player6, SkinId.Skin1)),
            new(new(CharacterId.Player6, SkinId.Skin2)),
            new(new(CharacterId.Player6, SkinId.Skin3)),
            new(new(CharacterId.Player6, SkinId.Skin4)),
            new(new(CharacterId.Player6, SkinId.Skin5)),

            new(new(CharacterId.Mob1, SkinId.Skin0)),
            new(new(CharacterId.Mob2, SkinId.Skin0)),
            new(new(CharacterId.Mob3, SkinId.Skin0)),
            new(new(CharacterId.Mob4, SkinId.Skin0)),

            new(new(CharacterId.Chief1, SkinId.Skin0)),
            new(new(CharacterId.Chief2, SkinId.Skin0)),

            new(new(CharacterId.Boss1, SkinId.Skin0)),
            new(new(CharacterId.Boss2, SkinId.Skin0)),
            new(new(CharacterId.Boss3, SkinId.Skin0)),
            new(new(CharacterId.Boss4, SkinId.Skin0)),
            new(new(CharacterId.Boss5, SkinId.Skin0)),
            new(new(CharacterId.Boss6, SkinId.Skin0)),

            new(new(CharacterId.Plant1, SkinId.Skin0)),
            new(new(CharacterId.Plant2, SkinId.Skin0)),
            new(new(CharacterId.Plant3, SkinId.Skin0)),
            new(new(CharacterId.Plant4, SkinId.Skin0)),
            new(new(CharacterId.Plant5, SkinId.Skin0)),
            new(new(CharacterId.Plant6, SkinId.Skin0)),
            new(new(CharacterId.Plant7, SkinId.Skin0)),
            new(new(CharacterId.Plant8, SkinId.Skin0)),

            new(new(CharacterId.Animal1, SkinId.Skin0)),
            new(new(CharacterId.Animal2, SkinId.Skin0)),
            new(new(CharacterId.Animal3, SkinId.Skin0)),
            new(new(CharacterId.Animal4, SkinId.Skin0)),
            new(new(CharacterId.Animal5, SkinId.Skin0)),

            new(new(CharacterId.Summon1, SkinId.Skin0)),

            new(new(CharacterId.Box, SkinId.Skin0)),

            new(new(CharacterId.Roadworks, SkinId.Skin0)),

            new(new(CharacterId.Fence1, SkinId.Skin0)),

            new(new(CharacterId.Landmark1, SkinId.Skin0)),

            new(new(CharacterId.Barrier1, SkinId.Skin0)),

            new(new(CharacterId.Water1, SkinId.Skin0)),

            new(new(CharacterId.Missile1, SkinId.Skin0)),
            new(new(CharacterId.Missile1, SkinId.Skin1)),
            new(new(CharacterId.Missile1, SkinId.Skin2)),
            new(new(CharacterId.Missile1, SkinId.Skin3)),
            new(new(CharacterId.Missile1, SkinId.Skin4)),
            new(new(CharacterId.Missile1, SkinId.Skin5)),

            new(new(CharacterId.Missile2, SkinId.Skin0)),
            new(new(CharacterId.Missile2, SkinId.Skin1)),
            new(new(CharacterId.Missile2, SkinId.Skin2)),
            new(new(CharacterId.Missile2, SkinId.Skin3)),
            new(new(CharacterId.Missile2, SkinId.Skin4)),
            new(new(CharacterId.Missile2, SkinId.Skin5)),

            new(new(CharacterId.Missile3, SkinId.Skin0)),
            new(new(CharacterId.Missile3, SkinId.Skin1)),
            new(new(CharacterId.Missile3, SkinId.Skin2)),
            new(new(CharacterId.Missile3, SkinId.Skin3)),
            new(new(CharacterId.Missile3, SkinId.Skin4)),
            new(new(CharacterId.Missile3, SkinId.Skin5)),

            new(new(CharacterId.Missile4, SkinId.Skin0)),
            new(new(CharacterId.Missile4, SkinId.Skin1)),
            new(new(CharacterId.Missile4, SkinId.Skin2)),
            new(new(CharacterId.Missile4, SkinId.Skin3)),
            new(new(CharacterId.Missile4, SkinId.Skin4)),
            new(new(CharacterId.Missile4, SkinId.Skin5)),

            new(new(CharacterId.Missile5, SkinId.Skin0)),
            new(new(CharacterId.Missile5, SkinId.Skin1)),
            new(new(CharacterId.Missile5, SkinId.Skin2)),
            new(new(CharacterId.Missile5, SkinId.Skin3)),
            new(new(CharacterId.Missile5, SkinId.Skin4)),
            new(new(CharacterId.Missile5, SkinId.Skin5)),

            new(new(CharacterId.Missile6, SkinId.Skin0)),
            new(new(CharacterId.Missile6, SkinId.Skin1)),
            new(new(CharacterId.Missile6, SkinId.Skin2)),
            new(new(CharacterId.Missile6, SkinId.Skin3)),
            new(new(CharacterId.Missile6, SkinId.Skin4)),
            new(new(CharacterId.Missile6, SkinId.Skin5)),

            new(new(CharacterId.Missile7, SkinId.Skin0)),
            new(new(CharacterId.Missile7, SkinId.Skin1)),
            new(new(CharacterId.Missile7, SkinId.Skin2)),
            new(new(CharacterId.Missile7, SkinId.Skin3)),
            new(new(CharacterId.Missile7, SkinId.Skin4)),
            new(new(CharacterId.Missile7, SkinId.Skin5)),

            new(new(CharacterId.Missile8, SkinId.Skin0)),
            new(new(CharacterId.Missile8, SkinId.Skin1)),
            new(new(CharacterId.Missile8, SkinId.Skin2)),
            new(new(CharacterId.Missile8, SkinId.Skin3)),
            new(new(CharacterId.Missile8, SkinId.Skin4)),
            new(new(CharacterId.Missile8, SkinId.Skin5)),

            new(new(CharacterId.Missile9, SkinId.Skin0)),
            new(new(CharacterId.Missile9, SkinId.Skin1)),
            new(new(CharacterId.Missile9, SkinId.Skin2)),
            new(new(CharacterId.Missile9, SkinId.Skin3)),
            new(new(CharacterId.Missile9, SkinId.Skin4)),
            new(new(CharacterId.Missile9, SkinId.Skin5)),

            new(new(CharacterId.Missile10, SkinId.Skin0)),
            new(new(CharacterId.Missile10, SkinId.Skin1)),
            new(new(CharacterId.Missile10, SkinId.Skin2)),
            new(new(CharacterId.Missile10, SkinId.Skin3)),
            new(new(CharacterId.Missile10, SkinId.Skin4)),
            new(new(CharacterId.Missile10, SkinId.Skin5)),

            new(new(CharacterId.Missile11, SkinId.Skin0)),
            new(new(CharacterId.Missile11, SkinId.Skin1)),
            new(new(CharacterId.Missile11, SkinId.Skin2)),
            new(new(CharacterId.Missile11, SkinId.Skin3)),
            new(new(CharacterId.Missile11, SkinId.Skin4)),
            new(new(CharacterId.Missile11, SkinId.Skin5)),

            new(new(CharacterId.Missile12, SkinId.Skin0)),
            new(new(CharacterId.Missile13, SkinId.Skin0)),
            new(new(CharacterId.Missile14, SkinId.Skin0)),
            new(new(CharacterId.Missile15, SkinId.Skin0)),
            new(new(CharacterId.Missile16, SkinId.Skin0)),
            new(new(CharacterId.Missile17, SkinId.Skin0)),
            new(new(CharacterId.Missile18, SkinId.Skin0)),
            new(new(CharacterId.Missile19, SkinId.Skin0)),
            new(new(CharacterId.Missile20, SkinId.Skin0)),
            new(new(CharacterId.Missile21, SkinId.Skin0)),
            new(new(CharacterId.Missile22, SkinId.Skin0)),
            new(new(CharacterId.Missile23, SkinId.Skin0)),
            new(new(CharacterId.Missile24, SkinId.Skin0)),
            new(new(CharacterId.Missile25, SkinId.Skin0)),
            new(new(CharacterId.Missile26, SkinId.Skin0)),
            new(new(CharacterId.Missile27, SkinId.Skin0)),
            new(new(CharacterId.Missile28, SkinId.Skin0)),
            new(new(CharacterId.Missile29, SkinId.Skin0)),
            new(new(CharacterId.Missile30, SkinId.Skin0)),
            new(new(CharacterId.Missile31, SkinId.Skin0)),
            new(new(CharacterId.Missile32, SkinId.Skin0)),

            new(new(CharacterId.Explosion1, SkinId.Skin0)),
            new(new(CharacterId.Explosion1, SkinId.Skin1)),
            new(new(CharacterId.Explosion1, SkinId.Skin2)),
            new(new(CharacterId.Explosion1, SkinId.Skin3)),
            new(new(CharacterId.Explosion1, SkinId.Skin4)),
            new(new(CharacterId.Explosion1, SkinId.Skin5)),

            new(new(CharacterId.Explosion2, SkinId.Skin0)),
            new(new(CharacterId.Explosion2, SkinId.Skin1)),
            new(new(CharacterId.Explosion2, SkinId.Skin2)),
            new(new(CharacterId.Explosion2, SkinId.Skin3)),
            new(new(CharacterId.Explosion2, SkinId.Skin4)),
            new(new(CharacterId.Explosion2, SkinId.Skin5)),

            new(new(CharacterId.Explosion3, SkinId.Skin0)),
            new(new(CharacterId.Explosion3, SkinId.Skin1)),
            new(new(CharacterId.Explosion3, SkinId.Skin2)),
            new(new(CharacterId.Explosion3, SkinId.Skin3)),
            new(new(CharacterId.Explosion3, SkinId.Skin4)),
            new(new(CharacterId.Explosion3, SkinId.Skin5)),

            new(new(CharacterId.Explosion4, SkinId.Skin0)),
            new(new(CharacterId.Explosion4, SkinId.Skin1)),
            new(new(CharacterId.Explosion4, SkinId.Skin2)),
            new(new(CharacterId.Explosion4, SkinId.Skin3)),
            new(new(CharacterId.Explosion4, SkinId.Skin4)),
            new(new(CharacterId.Explosion4, SkinId.Skin5)),

            new(new(CharacterId.Explosion5, SkinId.Skin0)),
            new(new(CharacterId.Explosion5, SkinId.Skin1)),
            new(new(CharacterId.Explosion5, SkinId.Skin2)),
            new(new(CharacterId.Explosion5, SkinId.Skin3)),
            new(new(CharacterId.Explosion5, SkinId.Skin4)),
            new(new(CharacterId.Explosion5, SkinId.Skin5)),

            new(new(CharacterId.Explosion6, SkinId.Skin0)),
            new(new(CharacterId.Explosion6, SkinId.Skin1)),
            new(new(CharacterId.Explosion6, SkinId.Skin2)),
            new(new(CharacterId.Explosion6, SkinId.Skin3)),
            new(new(CharacterId.Explosion6, SkinId.Skin4)),
            new(new(CharacterId.Explosion6, SkinId.Skin5)),

            new(new(CharacterId.Explosion7, SkinId.Skin0)),
            new(new(CharacterId.Explosion7, SkinId.Skin1)),
            new(new(CharacterId.Explosion7, SkinId.Skin2)),
            new(new(CharacterId.Explosion7, SkinId.Skin3)),
            new(new(CharacterId.Explosion7, SkinId.Skin4)),
            new(new(CharacterId.Explosion7, SkinId.Skin5)),

            new(new(CharacterId.Explosion8, SkinId.Skin0)),
            new(new(CharacterId.Explosion8, SkinId.Skin1)),
            new(new(CharacterId.Explosion8, SkinId.Skin2)),
            new(new(CharacterId.Explosion8, SkinId.Skin3)),
            new(new(CharacterId.Explosion8, SkinId.Skin4)),
            new(new(CharacterId.Explosion8, SkinId.Skin5)),

            new(new(CharacterId.Explosion9, SkinId.Skin0)),
            new(new(CharacterId.Explosion9, SkinId.Skin1)),
            new(new(CharacterId.Explosion9, SkinId.Skin2)),
            new(new(CharacterId.Explosion9, SkinId.Skin3)),
            new(new(CharacterId.Explosion9, SkinId.Skin4)),
            new(new(CharacterId.Explosion9, SkinId.Skin5)),

            new(new(CharacterId.Explosion10, SkinId.Skin0)),
            new(new(CharacterId.Explosion10, SkinId.Skin1)),
            new(new(CharacterId.Explosion10, SkinId.Skin2)),
            new(new(CharacterId.Explosion10, SkinId.Skin3)),
            new(new(CharacterId.Explosion10, SkinId.Skin4)),
            new(new(CharacterId.Explosion10, SkinId.Skin5)),

            new(new(CharacterId.Explosion11, SkinId.Skin0)),
            new(new(CharacterId.Explosion11, SkinId.Skin1)),
            new(new(CharacterId.Explosion11, SkinId.Skin2)),
            new(new(CharacterId.Explosion11, SkinId.Skin3)),
            new(new(CharacterId.Explosion11, SkinId.Skin4)),
            new(new(CharacterId.Explosion11, SkinId.Skin5)),

            new(new(CharacterId.Explosion12, SkinId.Skin0)),
            new(new(CharacterId.Explosion13, SkinId.Skin0)),
            new(new(CharacterId.Explosion14, SkinId.Skin0)),
            new(new(CharacterId.Explosion15, SkinId.Skin0)),
            new(new(CharacterId.Explosion16, SkinId.Skin0)),
            new(new(CharacterId.Explosion17, SkinId.Skin0)),
            new(new(CharacterId.Explosion18, SkinId.Skin0)),
            new(new(CharacterId.Explosion19, SkinId.Skin0)),
            new(new(CharacterId.Explosion20, SkinId.Skin0)),
            new(new(CharacterId.Explosion21, SkinId.Skin0)),
            new(new(CharacterId.Explosion22, SkinId.Skin0)),
            new(new(CharacterId.Explosion23, SkinId.Skin0)),
            new(new(CharacterId.Explosion24, SkinId.Skin0)),
            new(new(CharacterId.Explosion25, SkinId.Skin0)),
            new(new(CharacterId.Explosion26, SkinId.Skin0)),
            new(new(CharacterId.Explosion27, SkinId.Skin0)),
            new(new(CharacterId.Explosion28, SkinId.Skin0)),
            new(new(CharacterId.Explosion29, SkinId.Skin0)),
            new(new(CharacterId.Explosion30, SkinId.Skin0)),
            new(new(CharacterId.Explosion31, SkinId.Skin0)),
            new(new(CharacterId.Explosion32, SkinId.Skin0)),

            new(new(CharacterId.Magic1, SkinId.Skin0)),
            new(new(CharacterId.Magic2, SkinId.Skin0)),
            new(new(CharacterId.Magic3, SkinId.Skin0)),
            new(new(CharacterId.Magic4, SkinId.Skin0)),
            new(new(CharacterId.Magic5, SkinId.Skin0)),
            new(new(CharacterId.Magic7, SkinId.Skin0)),

            new(new(CharacterId.Booster1, SkinId.Skin0)),

            new(new(CharacterId.Specialty1, SkinId.Skin0)),
            new(new(CharacterId.Specialty2, SkinId.Skin0)),
            new(new(CharacterId.Specialty3, SkinId.Skin0)),
            new(new(CharacterId.Specialty4, SkinId.Skin0)),
            new(new(CharacterId.Specialty5, SkinId.Skin0)),
            new(new(CharacterId.Specialty6, SkinId.Skin0)),
            new(new(CharacterId.Specialty7, SkinId.Skin0)),
            new(new(CharacterId.Specialty8, SkinId.Skin0)),
            new(new(CharacterId.Specialty9, SkinId.Skin0)),
            new(new(CharacterId.Specialty10, SkinId.Skin0)),
            new(new(CharacterId.Specialty11, SkinId.Skin0)),
            new(new(CharacterId.Specialty12, SkinId.Skin0)),
            new(new(CharacterId.Specialty13, SkinId.Skin0)),
            new(new(CharacterId.Specialty14, SkinId.Skin0)),
            new(new(CharacterId.Specialty15, SkinId.Skin0)),
            new(new(CharacterId.Specialty16, SkinId.Skin0)),
            new(new(CharacterId.Specialty17, SkinId.Skin0)),
            new(new(CharacterId.Specialty18, SkinId.Skin0)),
            new(new(CharacterId.Specialty19, SkinId.Skin0)),
            new(new(CharacterId.Specialty20, SkinId.Skin0)),
            new(new(CharacterId.Specialty21, SkinId.Skin0)),
            new(new(CharacterId.Specialty22, SkinId.Skin0)),
            new(new(CharacterId.Specialty23, SkinId.Skin0)),
            new(new(CharacterId.Specialty24, SkinId.Skin0)),
            new(new(CharacterId.Specialty25, SkinId.Skin0)),
            new(new(CharacterId.Specialty26, SkinId.Skin0)),
            new(new(CharacterId.Specialty27, SkinId.Skin0)),
            new(new(CharacterId.Specialty28, SkinId.Skin0)),
            new(new(CharacterId.Specialty29, SkinId.Skin0)),
            new(new(CharacterId.Specialty30, SkinId.Skin0)),

            new(new(CharacterId.WarpOut1, SkinId.Skin0)),
            new(new(CharacterId.WarpOut2, SkinId.Skin0)),
            new(new(CharacterId.WarpIn1, SkinId.Skin0)),
            new(new(CharacterId.WarpIn2, SkinId.Skin0)),

            new(new(CharacterId.Like0, SkinId.Skin0)),
            new(new(CharacterId.Like1, SkinId.Skin0)),
            new(new(CharacterId.Like2, SkinId.Skin0)),
            new(new(CharacterId.Like3, SkinId.Skin0)),
            new(new(CharacterId.Like4, SkinId.Skin0)),
            new(new(CharacterId.Like5, SkinId.Skin0)),
            new(new(CharacterId.Like6, SkinId.Skin0)),
            new(new(CharacterId.Like7, SkinId.Skin0)),
            new(new(CharacterId.Like8, SkinId.Skin0)),
        };
    }
}
