using System.Collections.Generic;

namespace Some1.Play.Info.Alpha
{
    public static class AlphaCharacterCastInfosFactory
    {
        public static IEnumerable<CharacterCastInfo> Create() => new CharacterCastInfo[]
        {
            new(
                new(CharacterId.Player1, CastId.Attack),
                0.4f,
                1.35f,
                4,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    7.67f,
                    PlayConst.UnitShootAimPotition,
                    30,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Player1, CastId.Super),
                0.5f,
                10,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    7.67f,
                    PlayConst.UnitShootAimPotition,
                    50,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            //new(
            //    new(CharacterId.Player1, CastId.Ultra),
            //    0.5f,
            //    8,
            //    1,
            //    false,
            //    new(false, 0, 0),
            //    new(
            //        CastAimType.None,
            //        new(AreaType.Circle, default, 0.5f),
            //        7.67f,
            //        PlayConst.UnitShootAimPotition,
            //        0,
            //        new(CharacterType.Unit, Attribute.Neutral, TeamRelationInfo.Enemy),
            //        BumpLevel.Middle),
            //    new(Trait.All)),

            new(
                new(CharacterId.Player2, CastId.Attack),
                0.7f,
                0.72f,
                4,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 1.2f),
                    3,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Player2, CastId.Super),
                0.5f,
                10,
                1,
                false,
                new(false, 0, 0),
                new(
                    CastAimType.Self,
                    new(AreaType.Circle, default, 0),
                    0,
                    0,
                    0,
                    ObjectTargetInfo.None,
                    null)),

            new(
                new(CharacterId.Player3, CastId.Attack),
                0.7f,
                1.26f,
                4,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 0.7f),
                    9,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Player3, CastId.Super),
                1.4f,
                10,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 1),
                    11,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),

            new(
                new(CharacterId.Player4, CastId.Attack),
                0.4f,
                1.44f,
                4,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    7,
                    PlayConst.UnitShootAimPotition,
                    30,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Player4, CastId.Super),
                0.5f,
                10,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 1),
                    7,
                    1.2f,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Ally),
                    BumpLevel.High)),

            new(
                new(CharacterId.Player5, CastId.Attack),
                0.4f,
                1.8f,
                4,
                false,
                new(true, 0, 7.33f),
                new(
                    CastAimType.Jump,
                    new(AreaType.Circle, default, 4),
                    7.33f,
                    0,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.High)),
            new(
                new(CharacterId.Player5, CastId.Super),
                0.6f,
                10,
                1,
                false,
                new(true, 0, 7.33f),
                new(
                    CastAimType.Jump,
                    new(AreaType.Circle, default, 4),
                    7.33f,
                    0,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.High)),

            new(
                new(CharacterId.Player6, CastId.Attack),
                0.4f,
                1.26f,
                4,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    8.67f,
                    PlayConst.UnitShootAimPotition,
                    22.5f,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Player6, CastId.Super),
                0.5f,
                10,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 1),
                    2.67f,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),

            new(
                new(CharacterId.Mob1, CastId.Attack),
                2,
                5,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 0.5f),
                    3,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),

            new(
                new(CharacterId.Mob2, CastId.Attack),
                2,
                4,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 0.5f),
                    6,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),

            new(
                new(CharacterId.Mob3, CastId.Attack),
                2,
                5,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 0.5f),
                    8,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),

            new(
                new(CharacterId.Mob4, CastId.Attack),
                2,
                4,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 0.5f),
                    5,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),

            new(
                new(CharacterId.Chief1, CastId.Attack),
                2,
                4,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    3.67f,
                    PlayConst.UnitShootAimPotition,
                    65,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Chief1, CastId.Super),
                2,
                10,
                1,
                false,
                new(false, 0, 0),
                new(
                    CastAimType.Jump,
                    new(AreaType.Circle, default, 4),
                    0,
                    0,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.High)),

            new(
                new(CharacterId.Chief2, CastId.Attack),
                2,
                4,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    7.67f,
                    PlayConst.UnitShootAimPotition,
                    45,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Chief2, CastId.Super),
                2,
                10,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    10,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),

            new(
                new(CharacterId.Boss1, CastId.Attack),
                2,
                4,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    9,
                    PlayConst.UnitShootAimPotition,
                    90,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Boss1, CastId.Super),
                2,
                10,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    11,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Boss1, CastId.Ultra),
                2,
                10,
                1,
                false,
                new(false, 0, 0),
                new(
                    CastAimType.Self,
                    new(AreaType.Circle, default, 0),
                    0,
                    0,
                    0,
                    ObjectTargetInfo.None,
                    null),
                new(Trait.All)),

            new(
                new(CharacterId.Boss2, CastId.Attack),
                2,
                4,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    9,
                    PlayConst.UnitShootAimPotition,
                    90,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Boss2, CastId.Super),
                2,
                10,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    11,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Boss2, CastId.Ultra),
                2,
                10,
                1,
                false,
                new(false, 0, 0),
                new(
                    CastAimType.Self,
                    new(AreaType.Circle, default, 0),
                    0,
                    0,
                    0,
                    ObjectTargetInfo.None,
                    null),
                new(Trait.All)),

            new(
                new(CharacterId.Boss3, CastId.Attack),
                2,
                4,
                1,
                false,
                new(true, 1, 9),
                new(
                    CastAimType.Jump,
                    new(AreaType.Circle, default, 0.5f),
                    9,
                    0,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.High)),
            new(
                new(CharacterId.Boss3, CastId.Super),
                2,
                10,
                1,
                false,
                new(true, 1, 9),
                new(
                    CastAimType.Jump,
                    new(AreaType.Circle, default, 0.5f),
                    9,
                    0,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.High)),
            new(
                new(CharacterId.Boss3, CastId.Ultra),
                2,
                10,
                1,
                false,
                new(false, 0, 0),
                new(
                    CastAimType.Self,
                    new(AreaType.Circle, default, 0),
                    0,
                    0,
                    0,
                    ObjectTargetInfo.None,
                    null),
                new(Trait.All)),

            new(
                new(CharacterId.Boss4, CastId.Attack),
                1,
                2.5f,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 0.5f),
                    3,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Boss4, CastId.Super),
                1,
                3,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 0.5f),
                    9,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.High)),
            new(
                new(CharacterId.Boss4, CastId.Ultra),
                1,
                3,
                1,
                false,
                new(true, 0, 11),
                new(
                    CastAimType.Jump,
                    new(AreaType.Circle, default, 0.5f),
                    11,
                    0,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.High),
                new(Trait.All)),

            new(
                new(CharacterId.Boss5, CastId.Attack),
                1,
                2.5f,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 0.5f),
                    3,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Boss5, CastId.Super),
                1,
                3,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    9,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.High)),
            new(
                new(CharacterId.Boss5, CastId.Ultra),
                1,
                3,
                1,
                false,
                new(true, 0, 11),
                new(
                    CastAimType.Jump,
                    new(AreaType.Circle, default, 0.5f),
                    11,
                    0,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.High),
                new(Trait.All)),

            new(
                new(CharacterId.Boss6, CastId.Attack),
                1,
                2.5f,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 0.5f),
                    3,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
            new(
                new(CharacterId.Boss6, CastId.Super),
                1,
                3,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.CircularSector,
                    new(AreaType.Circle, default, 0.5f),
                    9,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.High)),
            new(
                new(CharacterId.Boss6, CastId.Ultra),
                1,
                3,
                1,
                false,
                new(true, 0, 11),
                new(
                    CastAimType.Jump,
                    new(AreaType.Circle, default, 0.5f),
                    11,
                    0,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.High),
                new(Trait.All)),

            CreateAnimalAttack(CharacterId.Animal1),
            CreateAnimalSuper(CharacterId.Animal1),
            CreateAnimalAttack(CharacterId.Animal2),
            CreateAnimalSuper(CharacterId.Animal2),
            CreateAnimalAttack(CharacterId.Animal3),
            CreateAnimalSuper(CharacterId.Animal3),
            CreateAnimalAttack(CharacterId.Animal4),
            CreateAnimalSuper(CharacterId.Animal4),
            CreateAnimalAttack(CharacterId.Animal5),
            CreateAnimalSuper(CharacterId.Animal5),

            new(
                new(CharacterId.Summon1, CastId.Attack),
                2,
                5,
                1,
                false,
                new(true, 0, 0),
                new(
                    CastAimType.Straight,
                    new(AreaType.Circle, default, 0.5f),
                    3,
                    PlayConst.UnitShootAimPotition,
                    0,
                    new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                    BumpLevel.Middle)),
        };

        private static CharacterCastInfo CreateAnimalAttack(CharacterId characterId) => new(
            new(characterId, CastId.Attack),
            2,
            5,
            1,
            false,
            new(true, 0, 0),
            new(
                CastAimType.Straight,
                new(AreaType.Circle, default, 0.5f),
                3,
                PlayConst.UnitShootAimPotition,
                0,
                new(CharacterTypeTarget.Unit, TeamTargetInfo.Enemy),
                BumpLevel.Middle));

        private static CharacterCastInfo CreateAnimalSuper(CharacterId characterId) => new(
            new(characterId, CastId.Super),
            2,
            5,
            1,
            false,
            new(true, 0, 0),
            new(
                CastAimType.Self,
                new(AreaType.Circle, default, 0),
                0,
                0,
                0,
                ObjectTargetInfo.None,
                BumpLevel.High));
    }
}
