using Some1.Resources;

namespace Some1.Localizing
{
    partial class StringSetFactory
    {
        private static StringSet Create_en_US()
        {
            return new(new()
            {
                { "Logo_Primary", "Star Star Star" },
                { "Logo_Secondary", "Multiplayer Shooter Game" },
                { "Copyright", "" },

                { "Common_Alert", "Alert" },
                { "Common_Error", "Error" },
                { "Common_Retry", "Retry" },
                { "Common_Cancel", "Cancel" },
                { "Common_OK", "OK" },
                { "Common_Selected", "Selected" },
                { "Common_Yes", "Yes" },
                { "Common_No", "No" },

                { "Common_Culture_Name", "Language" },
                { "Common_Theme_Name", "Theme" },
                { "Common_Theme_Name_Light", "Light theme" },
                { "Common_Theme_Name_Dark", "Dark theme" },

                { "Server_Region_Name_InMemoryAlpha", "In memory alpha" },
                { "Server_Region_Name_InMemoryBeta", "In memory beta" },
                { "Server_Region_Name_AsiaPacific", "Asia Pacific" },
                { "Server_Region_Name_Europe", "Europe" },
                { "Server_Region_Name_USEast", "US East" },
                { "Server_Region_Name_USWest", "US West" },
                { "Server_Region_Name_Canada", "Canada" },
                { "Server_Region_Name_SouthAmerica", "South America" },

                { "Server_City_Name_InMemoryAlpha", "In memory alpha" },
                { "Server_City_Name_InMemoryBeta", "In memory beta" },
                { "Server_City_Name_Seoul", "Seoul" },
                { "Server_City_Name_Daegeon", "Daejeon" },
                { "Server_City_Name_Busan", "Busan" },
                { "Server_City_Name_Tokyo", "Tokyo" },
                { "Server_City_Name_Osaka", "Osaka" },
                { "Server_City_Name_Singapore", "Singapore" },
                { "Server_City_Name_Mumbai", "Mumbai" },
                { "Server_City_Name_HongKong", "Hong Kong" },
                { "Server_City_Name_Stockholm", "Stockholm" },
                { "Server_City_Name_Sydney", "Sydney" },
                { "Server_City_Name_Frankfurt", "Frankfurt" },
                { "Server_City_Name_Paris", "Paris" },
                { "Server_City_Name_London", "London" },
                { "Server_City_Name_Ireland", "Ireland" },
                { "Server_City_Name_Virginia", "Virginia" },
                { "Server_City_Name_Ohio", "Ohio" },
                { "Server_City_Name_California", "California" },
                { "Server_City_Name_Oregon", "Oregon" },
                { "Server_City_Name_Central", "Central" },
                { "Server_City_Name_Calgary", "Calgary" },
                { "Server_City_Name_Montreal", "Montreal" },
                { "Server_City_Name_SaoPaulo", "SaoPaulo" },

                { "Server_Channel", "Channel" },

                { "Prefs_MusicVolume_Name", "Music volume" },
                { "Prefs_MusicVolume_Name_On", "Music On" },
                { "Prefs_MusicVolume_Name_Off", "Music Off" },
                { "Prefs_SoundVolume_Name", "Sound volume" },
                { "Prefs_SoundVolume_Name_On", "Sound On" },
                { "Prefs_SoundVolume_Name_Off", "Sound Off" },
                { "Prefs_UISize_Name", "UI size" },
                { "Prefs_UISize_Name_Big", "Big" },
                { "Prefs_UISize_Name_Small", "Small" },
                { "Prefs_CameraMode_Name", "Camera mode" },
                { "Prefs_CameraMode_Name_Fit", "Fit" },
                { "Prefs_CameraMode_Name_Fill", "Fill" },
                { "Prefs_GraphicQuality_Name", "Graphic quality" },
                { "Prefs_GraphicQuality_Name_Medium", "Medium" },
                { "Prefs_GraphicQuality_Name_High", "High" },
                { "Prefs_GraphicQuality_Name_Low", "Low" },
                { "Prefs_Fps_Name", "Frames per second" },
                { "Prefs_Fps_Name_Target60", "60" },
                { "Prefs_Fps_Name_Target120", "120" },
                { "Prefs_Fps_Name_Target240", "240" },
                { "Prefs_Fps_Name_Target30", "30" },
                { "Prefs_WalkJoystickHold_Name", "Move joystick hold" },
                { "Prefs_WalkJoystickHold_Name_False", "False" },
                { "Prefs_WalkJoystickHold_Name_True", "True" },
                { "Prefs_JitterBuffer_Name", "Jitter Buffer" },
                { "Prefs_JitterBuffer_Name_Large", "Large (150ms)" },
                { "Prefs_JitterBuffer_Name_Medium", "Medium (100ms)" },
                { "Prefs_JitterBuffer_Name_Small", "Small (50ms)" },
                { "Prefs_Reset", "Reset all settings" },

                { "Auth_SignIn", "Sign in" },
                { "Auth_SignInWithGoogle", "Sign in with Google" },
                { "Auth_SignInWithEmail", "Sign in with email" },
                { "Auth_Email", "Email" },
                { "Auth_Password", "Password" },

                { "Wait_Enter", "Enter" },
                { "Wait_EnterWithManualChannelSelection", "Enter with manual channel selection" },
                { "Wait_Account", "Account" },
                { "Wait_UserId", "User ID" },
                { "Wait_Server", "Server" },
                { "Wait_OpeningSoon", "Opening soon" },
                { "Wait_Maintenance", "Maintenance" },
                { "Wait_NotBusy", "" },
                { "Wait_Busy", "Busy" },
                { "Wait_Full", "Full" },
                { "Wait_SelectServer", "Select server" },
                { "Wait_SignOut", "Sign out" },
                { "Wait_SelectServerNote", "We recommend Server nearby. If it's too far away, game input response may be delayed. You can change Server at any time and your game data will be continuous." },

                { "Wait_PlayServerDetail_Title", "Enter Channel" },

                { "Wait_BuyProductResult_Message_Purchased", "Your premium purchase has been completed." },
                { "Wait_BuyProductResult_Message_Deferred", "Your premium purchase has been deferred." },

                { "Wait_Error_Rpc", "Network connection failed." },
                { "Wait_Error_Front_ServerOpeningSoon", "Server is opening soon. Please check Server." },
                { "Wait_Error_Front_ServerMaintenance", "Server is under maintenance. Please check Server." },
                { "Wait_Error_Front_ServerFull", "The number of participants for Server has been exceeded. Please check Server." },
                { "Wait_Error_Front_ChannelOpeningSoon", "Channel is opening soon. Please check Channel." },
                { "Wait_Error_Front_ChannelMaintenance", "Channel is under maintenance. Please check Channel." },
                { "Wait_Error_Front_ChannelFull", "The number of participants for Channel has been exceeded. Please check Channel." },

                { "Play_Error_Socket", "Network connection failed." },

                { "Play_Terminated", "Network connection has been lost." },

                { "Play_Empty", "Empty" },
                { "Play_IsUnlocked", "Is unlocked" },
                { "Play_IsSelected", "Is selected" },
                { "Play_Select", "Select" },
                { "Play_Unselect", "Unselect" },

                { "Play_Title", "Player" },
                { "Play_Character", "Character" },
                { "Play_Specialty", "Item" },
                { "Play_Premium", "Premium" },
                { "Play_Season", "Season" },
                { "Play_Prefs", "Prefs" },
                { "Play_User", "Account" },
                { "Play_Help", "Help" },
                { "Play_Change", "Change" },
                { "Play_Region", "Region" },
                { "Play_Section", "Zone" },

                { "Play_Title_Star", "Star" },
                { "Play_Title_StarTotal", "Star Total" },
                { "Play_Title_StarCharacter", "Character Star" },
                { "Play_Title_StarSpecialty", "Item Star" },
                { "Play_Title_PlayerId", "Player ID" },
                { "Play_Title_Like", "Like" },
                { "Play_Title_LikeLevel", "Like level" },
                { "Play_Title_LikePoint", "Like point" },

                { "Play_Property", "Property" },
                { "Play_StarLevel", "Star" },
                { "Play_CharacterStarPoint", "XP" },
                { "Play_Skin", "Skin" },
                { "Play_IsRandomSkin", "Is random skin" },

                { "Play_SpecialtyStarPoint", "EA" },

                { "Play_IsPremium", "Is premium" },
                { "Play_Buy", "Buy" },
                { "Play_Product", "Product" },
                { "Play_Price", "Price" },
                { "Play_PremiumMessage", "Premium is a paid term product that unlocks all characters and skins." },
                { "Play_Premium_TimeLeft", "Time remaining" },
                { "Play_Premium_StoreStartingError", "Store error" },
                { "Play_Premium_ViewChangeHistory", "View history" },

                { "Wait_WaitPremiumLogReason_None", "-" },
                { "Wait_WaitPremiumLogReason_Purchase", "Purchase" },
                { "Wait_WaitPremiumLogReason_Refund", "Refund" },
                { "Wait_WaitPremiumLogReason_Reward", "Reward" },

                { "Play_PremiumLogGroup_Title", "Premium history" },
                { "Play_PremiumLogGroup_Loading", "Loading..." },
                { "Play_PremiumLogGroup_Error", "Error" },
                { "Play_PremiumLogGroup_Empty", "Empty" },

                { "Play_PremiumDetail_Title", "Premium history" },
                { "Play_PremiumDetail_Reason", "Reason" },
                { "Play_PremiumDetail_CreatedDate", "Date (yyyy-mm-dd)" },
                { "Play_PremiumDetail_PremiumChangedDays", "amount of change (day)" },
                { "Play_PremiumDetail_PremiumExpirationDate", "Expiration date (yyyy-mm-dd)" },
                { "Play_PremiumDetail_Note", "Note" },
                { "Play_PremiumDetail_PurchaseProductName", "Purchase product name" },
                { "Play_PremiumDetail_PurchaseOrderId", "Google Play transaction ID" },
                { "Play_PremiumDetail_PurchaseDate", "Google Play transaction date" },

                { "Play_ComingSoon", "Coming soon" },

                { "Play_Character_Name_Player1", "Dino" },
                { "Play_Character_Name_Player2", "Teddy" },
                { "Play_Character_Name_Player3", "Rabby" },
                { "Play_Character_Name_Player4", "Uni" },
                { "Play_Character_Name_Player5", "Chicky" },
                { "Play_Character_Name_Player6", "Monkky" },

                { "Play_Character_Description_Player1", "" },
                { "Play_Character_Description_Player2", "" },
                { "Play_Character_Description_Player3", "" },
                { "Play_Character_Description_Player4", "" },
                { "Play_Character_Description_Player5", "" },
                { "Play_Character_Description_Player6", "" },

                { "Play_CharacterRole", "Role" },
                { "Play_CharacterRole_DamageDealer", "Damage Dealer" },
                { "Play_CharacterRole_Tank", "Tank" },
                { "Play_CharacterRole_Support", "Support" },
                { "Play_CharacterRole_Assassin", "Assassin" },
                { "Play_CharacterRole_Controller", "Controller" },
                { "Play_CharacterRole_Marksman", "Marksman" },
                { "Play_CharacterRole_Artillery", "Artillery" },

                { "Play_CharacterSkin_Name_Player1_Skin0", "Dino's default skin" },
                { "Play_CharacterSkin_Name_Player1_Skin1", "Dino's skin1" },
                { "Play_CharacterSkin_Name_Player1_Skin2", "Dino's skin2" },
                { "Play_CharacterSkin_Name_Player1_Skin3", "Dino's skin3" },
                { "Play_CharacterSkin_Name_Player1_Skin4", "Dino's skin4" },
                { "Play_CharacterSkin_Name_Player1_Skin5", "Dino's skin5" },
                { "Play_CharacterSkin_Name_Player2_Skin0", "Teddy's default skin" },
                { "Play_CharacterSkin_Name_Player2_Skin1", "Teddy's skin1" },
                { "Play_CharacterSkin_Name_Player2_Skin2", "Teddy's skin2" },
                { "Play_CharacterSkin_Name_Player2_Skin3", "Teddy's skin3" },
                { "Play_CharacterSkin_Name_Player2_Skin4", "Teddy's skin4" },
                { "Play_CharacterSkin_Name_Player2_Skin5", "Teddy's skin5" },
                { "Play_CharacterSkin_Name_Player3_Skin0", "Rabby's default skin" },
                { "Play_CharacterSkin_Name_Player3_Skin1", "Rabby's skin1" },
                { "Play_CharacterSkin_Name_Player3_Skin2", "Rabby's skin2" },
                { "Play_CharacterSkin_Name_Player3_Skin3", "Rabby's skin3" },
                { "Play_CharacterSkin_Name_Player3_Skin4", "Rabby's skin4" },
                { "Play_CharacterSkin_Name_Player3_Skin5", "Rabby's skin5" },
                { "Play_CharacterSkin_Name_Player4_Skin0", "Uni's default skin" },
                { "Play_CharacterSkin_Name_Player4_Skin1", "Uni's skin1" },
                { "Play_CharacterSkin_Name_Player4_Skin2", "Uni's skin2" },
                { "Play_CharacterSkin_Name_Player4_Skin3", "Uni's skin3" },
                { "Play_CharacterSkin_Name_Player4_Skin4", "Uni's skin4" },
                { "Play_CharacterSkin_Name_Player4_Skin5", "Uni's skin5" },
                { "Play_CharacterSkin_Name_Player5_Skin0", "Chicky's default skin" },
                { "Play_CharacterSkin_Name_Player5_Skin1", "Chicky's skin1" },
                { "Play_CharacterSkin_Name_Player5_Skin2", "Chicky's skin2" },
                { "Play_CharacterSkin_Name_Player5_Skin3", "Chicky's skin3" },
                { "Play_CharacterSkin_Name_Player5_Skin4", "Chicky's skin4" },
                { "Play_CharacterSkin_Name_Player5_Skin5", "Chicky's skin5" },
                { "Play_CharacterSkin_Name_Player6_Skin0", "Monkky's default skin" },
                { "Play_CharacterSkin_Name_Player6_Skin1", "Monkky's skin1" },
                { "Play_CharacterSkin_Name_Player6_Skin2", "Monkky's skin2" },
                { "Play_CharacterSkin_Name_Player6_Skin3", "Monkky's skin3" },
                { "Play_CharacterSkin_Name_Player6_Skin4", "Monkky's skin4" },
                { "Play_CharacterSkin_Name_Player6_Skin5", "Monkky's skin5" },

                { "Play_Specialty_Name_Mob1", "Green Leaf Porin" },
                { "Play_Specialty_Name_Mob2", "Yellow Leaf Porin" },
                { "Play_Specialty_Name_Mob3", "Dark Stem Porin" },
                { "Play_Specialty_Name_Mob4", "Pink Stem Porin" },
                { "Play_Specialty_Name_Chief1", "Goggle Eye Racco" },
                { "Play_Specialty_Name_Chief2", "Heart Eye Racco" },
                { "Play_Specialty_Name_Boss1", "Yellow Hair Treey" },
                { "Play_Specialty_Name_Boss2", "Colorful Hair Treey" },
                { "Play_Specialty_Name_Boss3", "Red Eye Treey" },
                { "Play_Specialty_Name_Boss4", "Poison Piggy" },
                { "Play_Specialty_Name_Boss5", "Moss Piggy" },
                { "Play_Specialty_Name_Boss6", "Flower Piggy" },
                { "Play_Specialty_Name_Plant1", "Two leaf Herb" },
                { "Play_Specialty_Name_Plant2", "Three leaf Herb" },
                { "Play_Specialty_Name_Plant3", "Yellow Lotus" },
                { "Play_Specialty_Name_Plant4", "Fire Lotus" },
                { "Play_Specialty_Name_Plant5", "Carrot" },
                { "Play_Specialty_Name_Plant6", "Pumpkin" },
                { "Play_Specialty_Name_Plant7", "Mushroom" },
                { "Play_Specialty_Name_Plant8", "Poison Mushroom" },
                { "Play_Specialty_Name_Animal1", "Chick" },
                { "Play_Specialty_Name_Animal2", "Chicken" },
                { "Play_Specialty_Name_Animal3", "Duck" },
                { "Play_Specialty_Name_Animal4", "Dog" },
                { "Play_Specialty_Name_Animal5", "Cat" },
                { "Play_Specialty_Name_Animal6", "Precious Chick" },
                { "Play_Specialty_Name_Animal7", "Precious Chicken" },
                { "Play_Specialty_Name_Animal8", "Precious Duck" },
                { "Play_Specialty_Name_Animal9", "Precious Dog" },
                { "Play_Specialty_Name_Animal10", "Precious Cat" },

                { "Play_Specialty_Description_Mob1", "" },
                { "Play_Specialty_Description_Mob2", "" },
                { "Play_Specialty_Description_Mob3", "" },
                { "Play_Specialty_Description_Mob4", "" },
                { "Play_Specialty_Description_Chief1", "" },
                { "Play_Specialty_Description_Chief2", "" },
                { "Play_Specialty_Description_Boss1", "" },
                { "Play_Specialty_Description_Boss2", "" },
                { "Play_Specialty_Description_Boss3", "" },
                { "Play_Specialty_Description_Boss4", "" },
                { "Play_Specialty_Description_Boss5", "" },
                { "Play_Specialty_Description_Boss6", "" },
                { "Play_Specialty_Description_Plant1", "" },
                { "Play_Specialty_Description_Plant2", "" },
                { "Play_Specialty_Description_Plant3", "" },
                { "Play_Specialty_Description_Plant4", "" },
                { "Play_Specialty_Description_Plant5", "" },
                { "Play_Specialty_Description_Plant6", "" },
                { "Play_Specialty_Description_Plant7", "" },
                { "Play_Specialty_Description_Plant8", "" },
                { "Play_Specialty_Description_Animal1", "" },
                { "Play_Specialty_Description_Animal2", "" },
                { "Play_Specialty_Description_Animal3", "" },
                { "Play_Specialty_Description_Animal4", "" },
                { "Play_Specialty_Description_Animal5", "" },
                { "Play_Specialty_Description_Animal6", "" },
                { "Play_Specialty_Description_Animal7", "" },
                { "Play_Specialty_Description_Animal8", "" },
                { "Play_Specialty_Description_Animal9", "" },
                { "Play_Specialty_Description_Animal10", "" },

                { "Play_Product_Name_Product1", "Premium 30 Dyas" },
                { "Play_Product_Name_Product2", "Premium 90 Dyas" },
                { "Play_Product_Name_Product3", "Premium 180 Dyas" },

                { "Play_UnaryResult_Format_BuyProduct", "{0} has been purchased." },

                { "Play_FrontError_Message_Locked", "Not possible in locked state." },
                { "Play_FrontError_Message_InvalidOperation", "Not possible in current state.." },
                { "Play_FrontError_Message_Challenge", "Not possible in chanllenge." },
                { "Play_FrontError_Message_Dead", "Not possible in dead state." },
                { "Play_FrontError_Message_Field", "Not possible in field." },
                { "Play_FrontError_Message_ExceededMaximum", "Anything more is not possible." },

                { "Play_Medal_Name_None", "None" },
                { "Play_Medal_Name_Blossom", "Blossom medal" },
                { "Play_Medal_Name_Diamond", "Tulip medal" },
                { "Play_Medal_Name_Bronze", "Bronze medal" },
                { "Play_Medal_Name_Silver", "Silver medal" },
                { "Play_Medal_Name_Gold", "Gold medal" },

                { "Play_GameMode_Name", "Play mode" },
                { "Play_GameMode_Name_Challenge", "Challenge" },
                { "Play_GameMode_Name_Adventure", "Adventure" },
                { "Play_GameMode_Description_Challenge", "Hunt monsters and obtain items. Challenge your high score within the 2 minute time limit." },
                { "Play_GameMode_Description_Adventure", "Explore the world freely without time limits. Return when your exploration is complete. (Play State > Return)" },

                { "Play_Ranking_Number_Format_First", "{0}st" },
                { "Play_Ranking_Number_Format_Second", "{0}nd" },
                { "Play_Ranking_Number_Format_Third", "{0}rd" },
                { "Play_Ranking_Number_Format", "{0}th" },

                { "Play_Ranking_TimeLeftUntilUpdate", "until the update" },
                { "Play_Ranking_Updated", "Updated" },

                { "Play_Ago_Format_Now", "Now" },
                { "Play_Ago_Format_Seconds", "{0}s ago" },
                { "Play_Ago_Format_Minutes", "{0}m ago" },
                { "Play_Ago_Format_Hours", "{0}h ago" },
                { "Play_Ago_Format_Days", "{0}d ago" },

                { "Play_TimeSpan_Short_Format_Days", "{0}d {1}h {2}m" },
                { "Play_TimeSpan_Short_Format_Hours", "{0}h {1}m" },
                { "Play_TimeSpan_Short_Format_Minutes", "{0}m {1}s" },
                { "Play_TimeSpan_Short_Format_Seconds", "{0}s" },

                { "Play_Success", "Success" },
                { "Play_Failure", "Failure" },
                { "Play_IsSuccess", "Is success" },
                { "Play_Score", "Score" },
                { "Play_EndTime", "End time" },
                { "Play_PlayTime", "Play time" },

                { "Play_SectionType_Name_Town", "Town" },
                { "Play_SectionType_Name_Yard", "Yard" },
                { "Play_SectionType_Name_Field", "Field" },
                { "Play_SectionType_Name_Empty", "Empty" },
                { "Play_SectionType_Name_End", "End" },

                { "Play_Location", "Location" },
                { "Play_Location_RegionMap", "Region map" },
                { "Play_Location_Region", "Region" },
                { "Play_Location_Section", "Zone" },
                { "Play_Location_Server", "Server" },
                { "Play_Location_Channel", "Channel" },
                { "Play_Location_Exit", "Leave Channel" },
                { "Play_Location_Exit_Message", "Do you want to leave Channel?" },

                { "Play_Common_Score_Format", "{0:N0}pt" },
                { "Play_Common_Count_Format", "{0:N0}ea" },

                { "Play_GameArgs_PlayMode", "Play mode" },
                { "Play_GameArgs_SeasonScore", "Season score" },
                { "Play_GameArgs_SeasonRanking", "Season ranking" },

                { "Play_GameResult_PlayHistory", "Play history" },

                { "Play_GameDetail_PlayState", "Play state" },
                { "Play_GameDetail_Score", "Score" },
                { "Play_GameDetail_TimeRemaining", "Time remaining" },
                { "Play_GameDetail_ElapsedTime", "Elapsed time" },
                { "Play_GameDetail_SurvivalReturnReward", "Survival return reward" },
                { "Play_GameDetail_SurvivalReturnRewardNote", "If you acquire more than 10 types, the oldest item will be deleted. Pin it if you don't want it deleted." },
                { "Play_GameDetail_Return", "Return" },
                { "Play_GameDetail_ReturnAfter", "Return after {0}" },
                { "Play_GameDetail_Cancel", "Cancel" },

                { "Play_GameReady_Ready", "Play" },
                { "Play_GameReady_Cancel", "Cancel" },
                { "Play_GameReady_ObtainableXP", "Obtainable XP" },

                { "Play_GameToast_Start", "Start" },
                { "Play_GameToast_End", "End" },
                { "Play_GameToast_Ready", "Ready" },
                { "Play_GameToast_Return", "Return" },
                { "Play_GameToast_ReReady", "ReReady" },
                { "Play_GameToast_ReturnFaulted", "Return Failed" },
                { "Play_GameToast_ReturnFaulted_Description", "Act or get hit!" },
                { "Play_GameToast_OpenLastResultDetail", "More" },

                { "Play_Ranking_SeasonRanking", "Season ranking" },

                { "Play_CharacterGroup_PickTimeRemained", "Until today’s character change" },
                { "Play_CharacterGroup_PickWhenReturn", "When you return to town, today's character will change." },

                { "Play_CharacterDetail_IsPicked", "Is today's character" },
                { "Play_CharacterDetail_ExpTimeAgo", "XP time" },
                { "Play_CharacterDetail_Info", "Info" },
                { "Play_CharacterDetail_Skill", "Skill" },
                { "Play_CharacterDetail_Season", "Season" },
                { "Play_CharacterDetail_Health", "HP" },
                { "Play_CharacterDetail_WalkSpeed", "Movement speed" },

                { "Play_SpecialtyDetail_NumberTimeAgo", "EA time" },
                { "Play_SpecialtyDetail_Info", "Info" },
                { "Play_SpecialtyDetail_Season", "Season" },
                { "Play_SpecialtyDetail_Region", "Region" },

                { "Play_Skill_Name_Skill1", "Skill1" },
                { "Play_Skill_Name_Skill2", "Skill2" },
                { "Play_Skill_Name_Skill3", "Skill3" },
                { "Play_Skill_Name_Skill4", "Skill4" },

                { "Play_Character_Master", "Master" },
                { "Play_Character_Todays", "Today's" },

                { "Play_Character_Skill_Name_Player1_Skill1", "Dino's skill1" },
                { "Play_Character_Skill_Name_Player1_Skill2", "Dino's skill2" },
                { "Play_Character_Skill_Name_Player2_Skill1", "Teddy's skill1" },
                { "Play_Character_Skill_Name_Player2_Skill2", "Teddy's skill2" },
                { "Play_Character_Skill_Name_Player3_Skill1", "Rabby's skill1" },
                { "Play_Character_Skill_Name_Player3_Skill2", "Rabby's skill2" },
                { "Play_Character_Skill_Name_Player4_Skill1", "Uni's skill1" },
                { "Play_Character_Skill_Name_Player4_Skill2", "Uni's skill2" },
                { "Play_Character_Skill_Name_Player5_Skill1", "Chicky's skill1" },
                { "Play_Character_Skill_Name_Player5_Skill2", "Chicky's skill2" },
                { "Play_Character_Skill_Name_Player6_Skill1", "Monkky's skill1" },
                { "Play_Character_Skill_Name_Player6_Skill2", "Monkky's skill2" },

                { "Play_Character_Skill_Description_Player1_Skill1", "" },
                { "Play_Character_Skill_Description_Player1_Skill2", "" },
                { "Play_Character_Skill_Description_Player2_Skill1", "" },
                { "Play_Character_Skill_Description_Player2_Skill2", "" },
                { "Play_Character_Skill_Description_Player3_Skill1", "" },
                { "Play_Character_Skill_Description_Player3_Skill2", "" },
                { "Play_Character_Skill_Description_Player4_Skill1", "" },
                { "Play_Character_Skill_Description_Player4_Skill2", "" },
                { "Play_Character_Skill_Description_Player5_Skill1", "" },
                { "Play_Character_Skill_Description_Player5_Skill2", "" },
                { "Play_Character_Skill_Description_Player6_Skill1", "" },
                { "Play_Character_Skill_Description_Player6_Skill2", "" },

                { "Play_SkillPropType_Damage", "Damage" },
                { "Play_SkillPropType_Range", "Range" },
                { "Play_SkillPropType_Reload", "Reload" },
                { "Play_SkillPropType_Defense", "Defense" },
                { "Play_SkillPropType_Duration", "Duration" },
                { "Play_SkillPropType_Recovery", "Recovery" },

                { "Play_WalkSpeed_VerySlow", "Very slow" },
                { "Play_WalkSpeed_Slow", "Slow" },
                { "Play_WalkSpeed_Normal", "Normal" },
                { "Play_WalkSpeed_Fast", "Fast" },
                { "Play_WalkSpeed_VeryFast", "Very fast" },

                { "Play_SkillRange_Short", "Short" },
                { "Play_SkillRange_Normal", "Normal" },
                { "Play_SkillRange_Long", "Long" },
                { "Play_SkillRange_VeryLong", "VeryLong" },

                { "Play_SkillReload_VerySlow", "Very slow" },
                { "Play_SkillReload_Slow", "Slow" },
                { "Play_SkillReload_Normal", "Normal" },
                { "Play_SkillReload_Fast", "Fast" },
                { "Play_SkillReload_VeryFast", "Very fast" },

                { "Play_User_Title", "Account" },

                { "Play_Help_Title", "Help" },
                { "Play_Help_Item_FAQ", "FAQ" },
                { "Play_Help_Item_About", "About" },

                { "Play_About_Title", "About" },

                { "TalkGroup_Title", "FAQ" },

                { "Talk_Welcome", "Welcome" },
                { "Talk_Server", "What is Server?" },
                { "Talk_PlayerId", "What is Player Id?" },
                { "Talk_DailyCharacter", "What is Daily Character?" },
                { "Talk_SurvivalReturnReward", "What is Survival return reward?" },
                { "Talk_ScoreRanking", "What is Ranking?" },
                { "Talk_GameResult", "What is Play History?" },
                { "Talk_ExitOnField", "What happens if I lose connection in the field?" },

                { "TalkMessage_Welcome_1", "H...Hi? Nice to meet you. My name is Dino. What about you guys?" },
                { "TalkMessage_Welcome_2", "Hi! I'm Teddy." },
                { "TalkMessage_Welcome_3", "I'm Rabby!" },
                { "TalkMessage_Welcome_4", "I'm Uni!" },
                { "TalkMessage_Welcome_5", "Chicky!" },
                { "TalkMessage_Welcome_6", "And, Monkky!" },
                { "TalkMessage_Welcome_7", "Okay, now that we're all here, shall we get started? Let's go!" },
                { "TalkMessage_Welcome_8", "L...Let's go!" },

                { "TalkMessage_Server_1", "What is Server?" },
                { "TalkMessage_Server_2", "Server is a computer that allows us to meet online. Server name is the name of the city, where Server physically runs." },
                { "TalkMessage_Server_3", "But... I can't find Server for the city I'm in." },
                { "TalkMessage_Server_4", "Sorry. Server can only be in cities supported by the cloud. We will try to run Servers in more cities in the future. Until then, please use another Server!" },

                { "TalkMessage_PlayerId_1", "What is Player Id?" },
                { "TalkMessage_PlayerId_2", "Player ID is a string that identifies a player within Channel. This may change when you reconnect, and there may be other people with the same player ID on other Channel!" },

                { "TalkMessage_DailyCharacter_1", "What is Daily Character?" },
                { "TalkMessage_DailyCharacter_2", "Today’s character is a character that can be used for free. It changes once a day. Dino, you and one other person were randomly selected, so there are two in total!" },

                { "TalkMessage_SurvivalReturnReward_1", "What is Survival return reward?" },
                { "TalkMessage_SurvivalReturnReward_2", "Survival return reward is items you can receive when you survive and return. You can possess a maximum of 10 types, but if you acquire more than 10 types, the oldest item is automatically deleted. If you don't want it to be automatically deleted, pin it. And if you don't survive and return, you'll lose all your rewards, so be careful!" },

                { "TalkMessage_ScoreRanking_1", "What is Ranking?" },
                { "TalkMessage_ScoreRanking_2", "Ranking is the challenge scores of players connected to Channel!" },

                { "TalkMessage_GameResult_1", "What is Play History?" },
                { "TalkMessage_GameResult_2", "The play record is the most recent play record. A maximum of 10 items can be recorded. Please note that if the score is 0, no record will be left!" },

                { "TalkMessage_ExitOnField_1", "What happens if I lose connection in the field?" },
                { "TalkMessage_ExitOnField_2", "If you lost connection in the field, your status will be retained on the server for 1 minute. If you are in combat, you will be defenseless and the play will eventually fail, so be careful!" },
            });
        }
    }
}
