using Some1.Resources;

namespace Some1.Localizing
{
    partial class StringSetFactory
    {
        private static StringSet Create_ko_KR()
        {
            return new(new()
            {
                { "Logo_Primary", "별별별" },
                { "Logo_Secondary", "멀티플레이어 슈팅 게임" },
                { "Copyright", "" },

                { "Common_Alert", "알림" },
                { "Common_Error", "오류" },
                { "Common_Retry", "재시도" },
                { "Common_Cancel", "취소" },
                { "Common_OK", "확인" },
                { "Common_Selected", "선택됨" },
                { "Common_Yes", "예" },
                { "Common_No", "아니오" },

                { "Common_Culture_Name", "언어" },
                { "Common_Theme_Name", "테마" },
                { "Common_Theme_Name_Light", "밝은 테마" },
                { "Common_Theme_Name_Dark", "어두운 테마" },

                { "Server_Region_Name_InMemoryAlpha", "인 메모리 알파" },
                { "Server_Region_Name_InMemoryBeta", "인 메모리 베타" },
                { "Server_Region_Name_AsiaPacific", "아시아 태평양" },
                { "Server_Region_Name_Europe", "유럽" },
                { "Server_Region_Name_USEast", "미국 동부" },
                { "Server_Region_Name_USWest", "미국 서부" },
                { "Server_Region_Name_Canada", "캐나다" },
                { "Server_Region_Name_SouthAmerica", "남아메리카" },

                { "Server_City_Name_InMemoryAlpha", "인 메모리 알파" },
                { "Server_City_Name_InMemoryBeta", "인 메모리 베타" },
                { "Server_City_Name_Seoul", "서울" },
                { "Server_City_Name_Daegeon", "대전" },
                { "Server_City_Name_Busan", "부산" },
                { "Server_City_Name_Tokyo", "도쿄" },
                { "Server_City_Name_Osaka", "오사카" },
                { "Server_City_Name_Singapore", "싱가포르" },
                { "Server_City_Name_Mumbai", "뭄바이" },
                { "Server_City_Name_HongKong", "홍콩" },
                { "Server_City_Name_Stockholm", "스톡홀름" },
                { "Server_City_Name_Sydney", "시드니" },
                { "Server_City_Name_Frankfurt", "프랑크푸르트" },
                { "Server_City_Name_Paris", "파리" },
                { "Server_City_Name_London", "런던" },
                { "Server_City_Name_Ireland", "아일랜드" },
                { "Server_City_Name_Virginia", "버지니아" },
                { "Server_City_Name_Ohio", "오하이오" },
                { "Server_City_Name_California", "캘리포니아" },
                { "Server_City_Name_Oregon", "오레곤" },
                { "Server_City_Name_Central", "중부" },
                { "Server_City_Name_Calgary", "캘거리" },
                { "Server_City_Name_Montreal", "몬트리올" },
                { "Server_City_Name_SaoPaulo", "상파울루" },

                { "Server_Channel", "채널" },

                { "Prefs_MusicVolume_Name", "배경음" },
                { "Prefs_MusicVolume_Name_On", "배경음 켜짐" },
                { "Prefs_MusicVolume_Name_Off", "배경음 꺼짐" },
                { "Prefs_SoundVolume_Name", "효과음" },
                { "Prefs_SoundVolume_Name_On", "효과음 켜짐" },
                { "Prefs_SoundVolume_Name_Off", "효과음 꺼짐" },
                { "Prefs_UISize_Name", "UI 사이즈" },
                { "Prefs_UISize_Name_Big", "크게" },
                { "Prefs_UISize_Name_Small", "작게" },
                { "Prefs_CameraMode_Name", "카메라 모드" },
                { "Prefs_CameraMode_Name_Fit", "맞춤" },
                { "Prefs_CameraMode_Name_Fill", "채움" },
                { "Prefs_GraphicQuality_Name", "그래픽 품질" },
                { "Prefs_GraphicQuality_Name_Medium", "중간" },
                { "Prefs_GraphicQuality_Name_High", "높음" },
                { "Prefs_GraphicQuality_Name_Low", "낮음" },
                { "Prefs_Fps_Name", "초당 프레임 수" },
                { "Prefs_Fps_Name_Target60", "60" },
                { "Prefs_Fps_Name_Target120", "120" },
                { "Prefs_Fps_Name_Target240", "240" },
                { "Prefs_Fps_Name_Target30", "30" },
                { "Prefs_WalkJoystickHold_Name", "이동 조이스틱 고정" },
                { "Prefs_WalkJoystickHold_Name_False", "아니오" },
                { "Prefs_WalkJoystickHold_Name_True", "예" },
                { "Prefs_JitterBuffer_Name", "Jitter Buffer" },
                { "Prefs_JitterBuffer_Name_Large", "Large (150ms)" },
                { "Prefs_JitterBuffer_Name_Medium", "Medium (100ms)" },
                { "Prefs_JitterBuffer_Name_Small", "Small (50ms)" },
                { "Prefs_Reset", "모든 설정 초기화" },

                { "Auth_SignIn", "로그인" },
                { "Auth_SignInWithGoogle", "구글로 로그인" },
                { "Auth_SignInWithEmail", "이메일로 로그인" },
                { "Auth_Email", "이메일" },
                { "Auth_Password", "비밀번호" },

                { "Wait_Enter", "입장" },
                { "Wait_EnterWithManualChannelSelection", "수동 채널 선택으로 입장" },
                { "Wait_Account", "계정" },
                { "Wait_UserId", "사용자 ID" },
                { "Wait_Server", "서버" },
                { "Wait_OpeningSoon", "오픈 예정" },
                { "Wait_Maintenance", "점검" },
                { "Wait_NotBusy", "" },
                { "Wait_Busy", "바쁨" },
                { "Wait_Full", "가득참" },
                { "Wait_SelectServer", "서버 선택" },
                { "Wait_SignOut", "로그아웃" },
                { "Wait_SelectServerNote", "가까운 서버를 추천합니다. 너무 멀면 게임 입력 반응이 늦어질 수 있습니다. 언제든지 서버를 변경 할 수 있으며 게임 데이터는 연속됩니다." },

                { "Wait_PlayServerDetail_Title", "채널 입장" },

                { "Wait_BuyProductResult_Message_Purchased", "프리미엄 구매가 완료되었습니다." },
                { "Wait_BuyProductResult_Message_Deferred", "프리미엄 구매가 Deferred되었습니다." },

                { "Wait_Error_Rpc", "네트워크 연결에 실패하였습니다." },
                { "Wait_Error_Front_ServerOpeningSoon", "서버 오픈 예정입니다. 서버를 확인해주세요." },
                { "Wait_Error_Front_ServerMaintenance", "서버 점검 중입니다. 서버를 확인해주세요." },
                { "Wait_Error_Front_ServerFull", "서버 입장 인원이 가득 찼습니다. 서버를 확인해주세요." },
                { "Wait_Error_Front_ChannelOpeningSoon", "채널 오픈 예정입니다. 채널을 확인해주세요." },
                { "Wait_Error_Front_ChannelMaintenance", "채널 점검 중입니다. 채널을 확인해주세요." },
                { "Wait_Error_Front_ChannelFull", "채널 입장 인원이 가득 찼습니다. 채널을 확인해주세요." },

                { "Play_Error_Socket", "네트워크 연결에 실패하였습니다." },

                { "Play_Terminated", "네트워크 연결이 끊어졌습니다." },

                { "Play_Empty", "비어 있음" },
                { "Play_IsUnlocked", "잠금 해제 여부" },
                { "Play_IsSelected", "선택 여부" },
                { "Play_Select", "선택" },
                { "Play_Unselect", "선택 해제" },

                { "Play_Title", "플레이어" },
                { "Play_Character", "캐릭터" },
                { "Play_Specialty", "아이템" },
                { "Play_Premium", "프리미엄" },
                { "Play_Season", "시즌" },
                { "Play_Prefs", "설정" },
                { "Play_User", "계정" },
                { "Play_Help", "도움말" },
                { "Play_Change", "변경" },
                { "Play_Region", "지역" },
                { "Play_Section", "영역" },

                { "Play_Title_Star", "별" },
                { "Play_Title_StarTotal", "별 합계" },
                { "Play_Title_StarCharacter", "캐릭터 별" },
                { "Play_Title_StarSpecialty", "아이템 별" },
                { "Play_Title_PlayerId", "플레이어 ID" },
                { "Play_Title_Like", "좋아요" },
                { "Play_Title_LikeLevel", "좋아요 레벨" },
                { "Play_Title_LikePoint", "좋아요 포인트" },

                { "Play_Property", "속성" },
                { "Play_StarLevel", "별" },
                { "Play_CharacterStarPoint", "경험치" },
                { "Play_Skin", "스킨" },
                { "Play_IsRandomSkin", "랜덤 스킨 여부" },

                { "Play_SpecialtyStarPoint", "수량" },

                { "Play_IsPremium", "프리미엄 여부" },
                { "Play_Buy", "구매" },
                { "Play_Product", "상품" },
                { "Play_Price", "가격" },
                { "Play_PremiumMessage", "프리미엄은 모든 캐릭터와 스킨을 잠금 해제하는 유료 기간제 상품입니다." },
                { "Play_Premium_TimeLeft", "남은 시간" },
                { "Play_Premium_StoreStartingError", "상점 오류" },
                { "Play_Premium_ViewChangeHistory", "내역 보기" },

                { "Wait_WaitPremiumLogReason_None", "-" },
                { "Wait_WaitPremiumLogReason_Purchase", "구매" },
                { "Wait_WaitPremiumLogReason_Refund", "환불" },
                { "Wait_WaitPremiumLogReason_Reward", "보상" },

                { "Play_PremiumLogGroup_Title", "프리미엄 내역" },
                { "Play_PremiumLogGroup_Loading", "불러오는 중..." },
                { "Play_PremiumLogGroup_Error", "오류" },
                { "Play_PremiumLogGroup_Empty", "비어있음" },

                { "Play_PremiumDetail_Title", "프리미엄 내역" },
                { "Play_PremiumDetail_Reason", "원인" },
                { "Play_PremiumDetail_CreatedDate", "날짜 (yyyy-mm-dd)" },
                { "Play_PremiumDetail_PremiumChangedDays", "변동량 (일)" },
                { "Play_PremiumDetail_PremiumExpirationDate", "만료 날짜 (yyyy-mm-dd)" },
                { "Play_PremiumDetail_Note", "비고" },
                { "Play_PremiumDetail_PurchaseProductName", "구매 상품명" },
                { "Play_PremiumDetail_PurchaseOrderId", "구글 플레이 거래 ID" },
                { "Play_PremiumDetail_PurchaseDate", "구글 플레이 거래 날짜 (yyyy-mm-dd)" },

                { "Play_ComingSoon", "출시 예정" },

                { "Play_Character_Name_Player1", "디노" },
                { "Play_Character_Name_Player2", "테디" },
                { "Play_Character_Name_Player3", "레비" },
                { "Play_Character_Name_Player4", "유니" },
                { "Play_Character_Name_Player5", "치키" },
                { "Play_Character_Name_Player6", "몬키" },

                { "Play_Character_Description_Player1", "" },
                { "Play_Character_Description_Player2", "" },
                { "Play_Character_Description_Player3", "" },
                { "Play_Character_Description_Player4", "" },
                { "Play_Character_Description_Player5", "" },
                { "Play_Character_Description_Player6", "" },

                { "Play_CharacterRole", "역할" },
                { "Play_CharacterRole_DamageDealer", "대미지 딜러" },
                { "Play_CharacterRole_Tank", "탱커" },
                { "Play_CharacterRole_Support", "서포터" },
                { "Play_CharacterRole_Assassin", "어쌔신" },
                { "Play_CharacterRole_Controller", "컨트롤러" },
                { "Play_CharacterRole_Marksman", "저격수" },
                { "Play_CharacterRole_Artillery", "투척수" },

                { "Play_CharacterSkin_Name_Player1_Skin0", "디노의 기본 스킨" },
                { "Play_CharacterSkin_Name_Player1_Skin1", "디노의 스킨1" },
                { "Play_CharacterSkin_Name_Player1_Skin2", "디노의 스킨2" },
                { "Play_CharacterSkin_Name_Player1_Skin3", "디노의 스킨3" },
                { "Play_CharacterSkin_Name_Player1_Skin4", "디노의 스킨4" },
                { "Play_CharacterSkin_Name_Player1_Skin5", "디노의 스킨5" },
                { "Play_CharacterSkin_Name_Player2_Skin0", "테디의 기본 스킨" },
                { "Play_CharacterSkin_Name_Player2_Skin1", "테디의 스킨1" },
                { "Play_CharacterSkin_Name_Player2_Skin2", "테디의 스킨2" },
                { "Play_CharacterSkin_Name_Player2_Skin3", "테디의 스킨3" },
                { "Play_CharacterSkin_Name_Player2_Skin4", "테디의 스킨4" },
                { "Play_CharacterSkin_Name_Player2_Skin5", "테디의 스킨5" },
                { "Play_CharacterSkin_Name_Player3_Skin0", "레비의 기본 스킨" },
                { "Play_CharacterSkin_Name_Player3_Skin1", "레비의 스킨1" },
                { "Play_CharacterSkin_Name_Player3_Skin2", "레비의 스킨2" },
                { "Play_CharacterSkin_Name_Player3_Skin3", "레비의 스킨3" },
                { "Play_CharacterSkin_Name_Player3_Skin4", "레비의 스킨4" },
                { "Play_CharacterSkin_Name_Player3_Skin5", "레비의 스킨5" },
                { "Play_CharacterSkin_Name_Player4_Skin0", "유니의 기본 스킨" },
                { "Play_CharacterSkin_Name_Player4_Skin1", "유니의 스킨1" },
                { "Play_CharacterSkin_Name_Player4_Skin2", "유니의 스킨2" },
                { "Play_CharacterSkin_Name_Player4_Skin3", "유니의 스킨3" },
                { "Play_CharacterSkin_Name_Player4_Skin4", "유니의 스킨4" },
                { "Play_CharacterSkin_Name_Player4_Skin5", "유니의 스킨5" },
                { "Play_CharacterSkin_Name_Player5_Skin0", "치키의 기본 스킨" },
                { "Play_CharacterSkin_Name_Player5_Skin1", "치키의 스킨1" },
                { "Play_CharacterSkin_Name_Player5_Skin2", "치키의 스킨2" },
                { "Play_CharacterSkin_Name_Player5_Skin3", "치키의 스킨3" },
                { "Play_CharacterSkin_Name_Player5_Skin4", "치키의 스킨4" },
                { "Play_CharacterSkin_Name_Player5_Skin5", "치키의 스킨5" },
                { "Play_CharacterSkin_Name_Player6_Skin0", "몬키의 기본 스킨" },
                { "Play_CharacterSkin_Name_Player6_Skin1", "몬키의 스킨1" },
                { "Play_CharacterSkin_Name_Player6_Skin2", "몬키의 스킨2" },
                { "Play_CharacterSkin_Name_Player6_Skin3", "몬키의 스킨3" },
                { "Play_CharacterSkin_Name_Player6_Skin4", "몬키의 스킨4" },
                { "Play_CharacterSkin_Name_Player6_Skin5", "몬키의 스킨5" },

                { "Play_Specialty_Name_Mob1", "초록잎 포린" },
                { "Play_Specialty_Name_Mob2", "노란잎 포린" },
                { "Play_Specialty_Name_Mob3", "어두운 줄기 포린" },
                { "Play_Specialty_Name_Mob4", "분홍 줄기 포린" },
                { "Play_Specialty_Name_Chief1", "고글눈 라코" },
                { "Play_Specialty_Name_Chief2", "하트눈 라코" },
                { "Play_Specialty_Name_Boss1", "노란 머리 트리" },
                { "Play_Specialty_Name_Boss2", "알록달록 머리 트리" },
                { "Play_Specialty_Name_Boss3", "빨간 눈 트리" },
                { "Play_Specialty_Name_Boss4", "독 피기" },
                { "Play_Specialty_Name_Boss5", "이끼 피기" },
                { "Play_Specialty_Name_Boss6", "꽃 피기" },
                { "Play_Specialty_Name_Plant1", "두 잎 허브" },
                { "Play_Specialty_Name_Plant2", "세 잎 허브" },
                { "Play_Specialty_Name_Plant3", "노란 연꽃" },
                { "Play_Specialty_Name_Plant4", "불 연꽃" },
                { "Play_Specialty_Name_Plant5", "당근" },
                { "Play_Specialty_Name_Plant6", "호박" },
                { "Play_Specialty_Name_Plant7", "버섯" },
                { "Play_Specialty_Name_Plant8", "독버섯" },
                { "Play_Specialty_Name_Animal1", "병아리" },
                { "Play_Specialty_Name_Animal2", "닭" },
                { "Play_Specialty_Name_Animal3", "오리" },
                { "Play_Specialty_Name_Animal4", "강아지" },
                { "Play_Specialty_Name_Animal5", "고양이" },
                { "Play_Specialty_Name_Animal6", "소중한 병아리" },
                { "Play_Specialty_Name_Animal7", "소중한 닭" },
                { "Play_Specialty_Name_Animal8", "소중한 오리" },
                { "Play_Specialty_Name_Animal9", "소중한 강아지" },
                { "Play_Specialty_Name_Animal10", "소중한 고양이" },

                { "Play_Specialty_Description_Mob1", "" },
                { "Play_Specialty_Description_Mob2", "" },
                { "Play_Specialty_Description_Mob3", "" },
                { "Play_Specialty_Description_Mob4", "" },
                { "Play_Specialty_Description_Chief1", "" },
                { "Play_Specialty_Description_Chief2", "" },
                { "Play_Specialty_Description_Boss1", "" },
                { "Play_Specialty_Description_Boss2", "" },
                { "Play_Specialty_Description_Boss3", "" },
                { "Play_Specialty_Description_Boss4", "" },
                { "Play_Specialty_Description_Boss5", "" },
                { "Play_Specialty_Description_Boss6", "" },
                { "Play_Specialty_Description_Plant1", "" },
                { "Play_Specialty_Description_Plant2", "" },
                { "Play_Specialty_Description_Plant3", "" },
                { "Play_Specialty_Description_Plant4", "" },
                { "Play_Specialty_Description_Plant5", "" },
                { "Play_Specialty_Description_Plant6", "" },
                { "Play_Specialty_Description_Plant7", "" },
                { "Play_Specialty_Description_Plant8", "" },
                { "Play_Specialty_Description_Animal1", "" },
                { "Play_Specialty_Description_Animal2", "" },
                { "Play_Specialty_Description_Animal3", "" },
                { "Play_Specialty_Description_Animal4", "" },
                { "Play_Specialty_Description_Animal5", "" },
                { "Play_Specialty_Description_Animal6", "" },
                { "Play_Specialty_Description_Animal7", "" },
                { "Play_Specialty_Description_Animal8", "" },
                { "Play_Specialty_Description_Animal9", "" },
                { "Play_Specialty_Description_Animal10", "" },

                { "Play_Product_Name_Product1", "프리미엄 30 일" },
                { "Play_Product_Name_Product2", "프리미엄 90 일" },
                { "Play_Product_Name_Product3", "프리미엄 180 일" },

                { "Play_UnaryResult_Format_BuyProduct", "{0} 구매가 완료되었습니다." },

                { "Play_FrontError_Message_Locked", "잠금 상태에서 불가능합니다." },
                { "Play_FrontError_Message_InvalidOperation", "현재 상태에서 불가능합니다." },
                { "Play_FrontError_Message_Challenge", "도전 중에 불가능합니다." },
                { "Play_FrontError_Message_Dead", "죽은 상태에서 불가능합니다." },
                { "Play_FrontError_Message_Field", "필드에서 불가능합니다." },
                { "Play_FrontError_Message_ExceededMaximum", "더 이상은 불가능합니다." },

                { "Play_Medal_Name_None", "없음" },
                { "Play_Medal_Name_Blossom", "꽃메달" },
                { "Play_Medal_Name_Tulip", "튤립메달" },
                { "Play_Medal_Name_Bronze", "동메달" },
                { "Play_Medal_Name_Silver", "은메달" },
                { "Play_Medal_Name_Gold", "금메달" },

                { "Play_GameMode_Name", "플레이 모드" },
                { "Play_GameMode_Name_Challenge", "도전" },
                { "Play_GameMode_Name_Adventure", "탐험" },
                { "Play_GameMode_Description_Challenge", "몬스터를 사냥해서 아이템을 획득하세요. 제한시간 2분 동안 높은 점수에 도전하세요." },
                { "Play_GameMode_Description_Adventure", "제한시간 없이 자유롭게 세계를 탐험하세요. 탐험이 완료되면 귀환하세요. (플레이 상태 > 귀환)" },

                { "Play_Ranking_Number_Format_First", "{0}위" },
                { "Play_Ranking_Number_Format_Second", "{0}위" },
                { "Play_Ranking_Number_Format_Third", "{0}위" },
                { "Play_Ranking_Number_Format", "{0}위" },

                { "Play_Ranking_TimeLeftUntilUpdate", "갱신까지" },
                { "Play_Ranking_Updated", "갱신됨" },

                { "Play_Ago_Format_Now", "방금" },
                { "Play_Ago_Format_Seconds", "{0}초 전" },
                { "Play_Ago_Format_Minutes", "{0}분 전" },
                { "Play_Ago_Format_Hours", "{0}시간 전" },
                { "Play_Ago_Format_Days", "{0}일 전" },

                { "Play_TimeSpan_Short_Format_Days", "{0}일 {1}시간 {2}분" },
                { "Play_TimeSpan_Short_Format_Hours", "{0}시간 {1}분" },
                { "Play_TimeSpan_Short_Format_Minutes", "{0}분 {1}초" },
                { "Play_TimeSpan_Short_Format_Seconds", "{0}초" },

                { "Play_Success", "성공" },
                { "Play_Failure", "실패" },
                { "Play_IsSuccess", "성공 여부" },
                { "Play_Score", "점수" },
                { "Play_EndTime", "종료 시간" },
                { "Play_PlayTime", "플레이 시간" },

                { "Play_SectionType_Name_Town", "마을" },
                { "Play_SectionType_Name_Yard", "마당" },
                { "Play_SectionType_Name_Field", "필드" },
                { "Play_SectionType_Name_Empty", "빈" },
                { "Play_SectionType_Name_End", "끝" },

                { "Play_Location", "위치" },
                { "Play_Location_RegionMap", "지역 지도" },
                { "Play_Location_Region", "지역" },
                { "Play_Location_Section", "영역" },
                { "Play_Location_Server", "서버" },
                { "Play_Location_Channel", "채널" },
                { "Play_Location_Exit", "채널에서 나가기" },
                { "Play_Location_Exit_Message", "채널에서 나가시겠습니까?" },

                { "Play_Common_Score_Format", "{0:N0}점" },
                { "Play_Common_Count_Format", "{0:N0}개" },

                { "Play_GameArgs_PlayMode", "플레이 모드" },
                { "Play_GameArgs_SeasonScore", "시즌 점수" },
                { "Play_GameArgs_SeasonRanking", "시즌 순위" },

                { "Play_GameResult_PlayHistory", "플레이 기록" },

                { "Play_GameDetail_PlayState", "플레이 상태" },
                { "Play_GameDetail_Score", "점수" },
                { "Play_GameDetail_TimeRemaining", "남은 시간" },
                { "Play_GameDetail_ElapsedTime", "경과 시간" },
                { "Play_GameDetail_SurvivalReturnReward", "생존 귀환 보상" },
                { "Play_GameDetail_SurvivalReturnRewardNote", "10가지 종류를 초과 획득하면 가장 오래된 아이템이 삭제됩니다. 삭제를 원하지 않으면 핀을 고정하세요." },
                { "Play_GameDetail_Return", "귀환" },
                { "Play_GameDetail_ReturnAfter", "{0} 후 귀환" },
                { "Play_GameDetail_Cancel", "취소" },

                { "Play_GameReady_Ready", "플레이" },
                { "Play_GameReady_Cancel", "취소" },
                { "Play_GameReady_ObtainableXP", "획득 가능한 경험치" },

                { "Play_GameToast_Start", "시작" },
                { "Play_GameToast_End", "끝" },
                { "Play_GameToast_Ready", "준비" },
                { "Play_GameToast_Return", "귀환" },
                { "Play_GameToast_ReReady", "재준비" },
                { "Play_GameToast_ReturnFaulted", "귀환 실패" },
                { "Play_GameToast_ReturnFaulted_Description", "행동했거나 타격받았어요!" },
                { "Play_GameToast_OpenLastResultDetail", "더 보기" },

                { "Play_Ranking_SeasonRanking", "시즌 순위" },

                { "Play_CharacterGroup_PickTimeRemained", "오늘의 캐릭터 변경까지" },
                { "Play_CharacterGroup_PickWhenReturn", "마을로 귀환하면 오늘의 캐릭터가 변경됩니다." },

                { "Play_CharacterDetail_IsPicked", "오늘의 캐릭터 여부" },
                { "Play_CharacterDetail_ExpTimeAgo", "경험치 획득 시간" },
                { "Play_CharacterDetail_Info", "정보" },
                { "Play_CharacterDetail_Skill", "스킬" },
                { "Play_CharacterDetail_Season", "시즌" },
                { "Play_CharacterDetail_Health", "생명력" },
                { "Play_CharacterDetail_WalkSpeed", "이동 속도" },

                { "Play_SpecialtyDetail_NumberTimeAgo", "획득 시간" },
                { "Play_SpecialtyDetail_Info", "정보" },
                { "Play_SpecialtyDetail_Season", "시즌" },
                { "Play_SpecialtyDetail_Region", "지역" },

                { "Play_Skill_Name_Skill1", "스킬1" },
                { "Play_Skill_Name_Skill2", "스킬2" },
                { "Play_Skill_Name_Skill3", "스킬3" },
                { "Play_Skill_Name_Skill4", "스킬4" },

                { "Play_Character_Master", "마스터" },
                { "Play_Character_Todays", "오늘의" },

                { "Play_Character_Skill_Name_Player1_Skill1", "디노의 스킬1" },
                { "Play_Character_Skill_Name_Player1_Skill2", "디노의 스킬2" },
                { "Play_Character_Skill_Name_Player2_Skill1", "테디의 스킬1" },
                { "Play_Character_Skill_Name_Player2_Skill2", "테디의 스킬2" },
                { "Play_Character_Skill_Name_Player3_Skill1", "레비의 스킬1" },
                { "Play_Character_Skill_Name_Player3_Skill2", "레비의 스킬2" },
                { "Play_Character_Skill_Name_Player4_Skill1", "유니의 스킬1" },
                { "Play_Character_Skill_Name_Player4_Skill2", "유니의 스킬2" },
                { "Play_Character_Skill_Name_Player5_Skill1", "치키의 스킬1" },
                { "Play_Character_Skill_Name_Player5_Skill2", "치키의 스킬2" },
                { "Play_Character_Skill_Name_Player6_Skill1", "몬키의 스킬1" },
                { "Play_Character_Skill_Name_Player6_Skill2", "몬키의 스킬2" },

                { "Play_Character_Skill_Description_Player1_Skill1", "" },
                { "Play_Character_Skill_Description_Player1_Skill2", "" },
                { "Play_Character_Skill_Description_Player2_Skill1", "" },
                { "Play_Character_Skill_Description_Player2_Skill2", "" },
                { "Play_Character_Skill_Description_Player3_Skill1", "" },
                { "Play_Character_Skill_Description_Player3_Skill2", "" },
                { "Play_Character_Skill_Description_Player4_Skill1", "" },
                { "Play_Character_Skill_Description_Player4_Skill2", "" },
                { "Play_Character_Skill_Description_Player5_Skill1", "" },
                { "Play_Character_Skill_Description_Player5_Skill2", "" },
                { "Play_Character_Skill_Description_Player6_Skill1", "" },
                { "Play_Character_Skill_Description_Player6_Skill2", "" },

                { "Play_SkillPropType_Damage", "피해량" },
                { "Play_SkillPropType_Range", "사정거리" },
                { "Play_SkillPropType_Reload", "재장전 속도" },
                { "Play_SkillPropType_Defense", "피해 감소량" },
                { "Play_SkillPropType_Duration", "지속 시간" },
                { "Play_SkillPropType_Recovery", "치유량" },

                { "Play_WalkSpeed_VerySlow", "매우 느림" },
                { "Play_WalkSpeed_Slow", "느림" },
                { "Play_WalkSpeed_Normal", "보통" },
                { "Play_WalkSpeed_Fast", "빠름" },
                { "Play_WalkSpeed_VeryFast", "매우 빠름" },

                { "Play_SkillRange_Short", "근거리" },
                { "Play_SkillRange_Normal", "보통" },
                { "Play_SkillRange_Long", "장거리" },
                { "Play_SkillRange_VeryLong", "초장거리" },

                { "Play_SkillReload_VerySlow", "매우 느림" },
                { "Play_SkillReload_Slow", "느림" },
                { "Play_SkillReload_Normal", "보통" },
                { "Play_SkillReload_Fast", "빠름" },
                { "Play_SkillReload_VeryFast", "매우 빠름" },

                { "Play_User_Title", "계정" },

                { "Play_Help_Title", "도움말" },
                { "Play_Help_Item_FAQ", "자주 묻는 질문" },
                { "Play_Help_Item_About", "About" },

                { "Play_About_Title", "About" },

                { "TalkGroup_Title", "자주 묻는 질문" },

                { "Talk_Welcome", "환영" },
                { "Talk_Server", "서버가 뭐야?" },
                { "Talk_PlayerId", "플레이어 ID가 뭐야?" },
                { "Talk_DailyCharacter", "오늘의 캐릭터가 뭐야?" },
                { "Talk_SurvivalReturnReward", "생존 귀환 보상이 뭐야?" },
                { "Talk_ScoreRanking", "랭킹이 뭐야?" },
                { "Talk_GameResult", "플레이 기록이 뭐야?" },
                { "Talk_ExitOnField", "필드에서 접속이 끊어지면 어떻게 돼?" },

                { "TalkMessage_Welcome_1", "안...안녕? 만나서 반가워. 내 이름은 디노야. 너희들은?" },
                { "TalkMessage_Welcome_2", "안녕! 나는 테디야." },
                { "TalkMessage_Welcome_3", "나는 레비야!" },
                { "TalkMessage_Welcome_4", "난, 유니!" },
                { "TalkMessage_Welcome_5", "치키!" },
                { "TalkMessage_Welcome_6", "그리고, 몬키!" },
                { "TalkMessage_Welcome_7", "자, 이제 모두 모였으니 출발해볼까? 출발!" },
                { "TalkMessage_Welcome_8", "출...출발!" },

                { "TalkMessage_Server_1", "서버가 뭐야?" },
                { "TalkMessage_Server_2", "서버는 우리가 온라인 상에서 만날수 있도록 해주는 컴퓨터야. 서버 이름은 도시 이름인데, 서버가 물리적으로 실행되는 곳이지." },
                { "TalkMessage_Server_3", "그런데... 내가 있는 도시의 서버를 찾을 수가 없어." },
                { "TalkMessage_Server_4", "미안해. 서버는 클라우드에서 지원하는 도시에만 있을 수 있어. 앞으로 더 많은 도시에서 서버를 실행하도록 노력할게. 그때까지는 다른 서버를 이용해줘!" },

                { "TalkMessage_PlayerId_1", "플레이어 ID가 뭐야?" },
                { "TalkMessage_PlayerId_2", "플레이어 ID는 채널 안에서 플레이어를 구별하는 문자야. 재접속하면 변경될 수 있고, 다른 채널에는 같은 플레이어 ID를 가진 다른 사람이 있을 수 있어!" },

                { "TalkMessage_DailyCharacter_1", "오늘의 캐릭터가 뭐야?" },
                { "TalkMessage_DailyCharacter_2", "오늘의 캐릭터는 무료로 이용 가능한 캐릭터야. 하루에 한번씩 변경돼. 디노 너와 또 한 명이 무작위로 선택돼서, 총 두 명이지!" },

                { "TalkMessage_SurvivalReturnReward_1", "생존 귀환 보상이 뭐야?" },
                { "TalkMessage_SurvivalReturnReward_2", "생존 귀환 보상은 생존 귀환하면 받을 수 있는 아이템이야. 최대 10가지를 소지할 수 있는데, 만약 10가지를 초과해서 습득하면 가장 오래된 아이템이 자동 삭제돼. 자동 삭제를 원하지 않으면 핀을 고정해놔. 그리고 생존해서 귀환하지 못하면 보상을 모두 잃어버리니 주의해!" },

                { "TalkMessage_ScoreRanking_1", "순위가 뭐야?" },
                { "TalkMessage_ScoreRanking_2", "순위는 채널에 접속 중인 플레이어들의 도전 점수 순위야!" },

                { "TalkMessage_GameResult_1", "플레이 기록이 뭐야?" },
                { "TalkMessage_GameResult_2", "플레이 기록은 최근 플레이한 기록이야. 최대 10개까지 기록되고, 점수가 0점이면 기록이 남지 않으니 참고해!" },

                { "TalkMessage_ExitOnField_1", "필드에서 접속이 끊어지면 어떻게 돼?" },
                { "TalkMessage_ExitOnField_2", "필드에서 접속이 끊어지면 서버에 너의 상태가 1분 동안 유지돼. 만약 전투 중이었다면 무방비 상태가 되고 결국 플레이가 실패하니 주의해!" },
            });
        }
    }
}
